#include "rooms.h"
#include "attribute.h"
#include "defines_cdfj.h"
#include "drawplayer.h"
#include "main.h"
#include "man.h"
#include "menu.h"
#include "random.h"
#include "score.h"
#include "scroll.h"

int pillCount;

// Sokoban level data

const struct roomDef room[] = {

// To add new rooms just place either compressed or uncompressed room here.
// Add '=' to pad outside-squares that are accidentally blank when drawn

// Format:  ID (or-1), width, height, pushes (or -1), moves (or -1), "... room string"
// The room string may be compressed or uncompressed. Use tools/compressroom.py to compress

#define NEXTLINE '|'
#define WALL '#'
#define PLAYERONGOAL '+'
#define PLAYERONNORMAL '@'
#define BOXONTARGET '*'
#define TARGET '.'
#define GAP ' '
#define GAP2 '-'
#define GAP3 '_'
#define BOX '$'
#define STEEL '='

#include "scrapedRooms.c"

#if 0
    {
        /*
        ######
        # . .#
        #.$  #
        # #$$#
        #.$ @#
        ######
        */

        50,
        6,
        6,
        7,
        16,
        "6#=|# . .#=|#.$2 #=|# #2$#=|#.$ @#=|6#",
    },
    {

        /*

        =#####|
        =#   #|
        ##.# #|
        # .  #|
        # *#$###|
        # *@$  #|
        # *#$# #|
        # .    #|
        ##  # ##|
        =##   #|
        ==#####

        Collection/Set: Kevin 13
        Serial Number: 69
        Name: Kevin 13 69
        Author: Kevin B. Reilly
        Width: 8
        Height: 11
        Nb Boxes: 6
        Pushes: 33
        Moves: 152
        */

        69,
        8,   // width
        11,  // height
        33,  // push
        152, // move

        "=5#|=#3 #|2#.# #|# .2 #|# *#$3#|# *@$2 #|# *#$# #|# .4 #|2#2 # 2#|=2#3 #|2=5#",

    },

    {

        /*
        "########|"
        "#   # .#|"
        "#    $*#|"
        "#   #@ #|"
        "########"
        Collection/Set: Mass Remodel
        Serial Number: 376
        Name: Mass Remodel 376
        Author: Many Authors, see each level
        Width: 8
        Height: 5
        Nb Boxes: 2
        Pushes: 8
        Moves: 13
        */

        376,
        8,
        5,
        8,
        13,
        "8#|#3 # .#|#4 $*#|#3 #@ #|8#",
    },

    {

        // ####
        // # .#
        // #  ###
        // #*@  #
        // #  $ #
        // #  ###
        // ####

        -1,
        6,
        7,
        21,
        21,
        "4#|# .#|#2 3#|#*@2 #|#2 $ #|#2 3#|4#",

    },

    {
        /*

        Collection/Set: Sokogen-990602 Levels
        Serial Number: 30
        Name: Sokogen-990602 Levels 30
        Author: Jacques Duthen
        Width: 7
        Height: 6
        Nb Boxes: 3
        Pushes: 11
        Moves: 39

        "#######|"
        "##.  ##|"
        "#+$$$ #|"
        "# #  .#|"
        "#    ##|"
        "#######"

        */

        -1, // ID
        7,  // width
        6,  // height
        11, // pushes
        39, // moves

        "7#|2#.2 2#|#+3$ #|# #2 .#|#4 2#|7#",
    },

    {

        /*

    ########|
    #  . ..#|
    #.$ #  #|
    # #$$$*#|
    #.$ @  #|
    ########
    Collection/Set: Bugs collection 2
    Serial Number: 57
    Name: Bugs collection 2 57
    Author: Buddy Casamis
    Width: 8
    Height: 6
    Nb Boxes: 6
    Pushes: 10
    Moves: 40

        */

        57,
        8,
        6,
        10,
        40,
        "8#|#2 . 2.#|#.$ #2 #|# #3$*#|#.$ @2 #|8#",

    },
    {

        /*

        ===#####|
        =###*. #|
        =#   . ##|
        =# #    #|
        ##  #.  #|
        # $*$   #|
        #.$  $ ##|
        #@##   #|
        ########
        Collection/Set: Ionic Catalysts
        Serial Number: 961
        Name: Ionic Catalysts 961
        Author: Razorflame
        Width: 9
        Height: 9
        Nb Boxes: 6
        Pushes: 30
        Moves: 77

        */
        961,
        9,
        9,
        30,
        77,
        "3=5#|=3#*. #|=#3 . 2#|=# #4 #|2#2 #.2 #|# $*$3 #|#.$2 $ 2#|#@2#3 #|8#",

    },

    {
        /*
        ########|
        #@ #.  #|
        #  #   #|
        #  #   #|
        # $ #$ #|
        # $    #|
        ####.. #|
        ===#####
        Collection/Set: TP5_99
        Serial Number: 57
        Name: TP5_99 #57
        Author: Taylor & Parberry AutoGenerated 1of5
        Width: 8
        Height: 8
        Nb Boxes: 3
        Pushes: 30
        Moves: 88

        */
        57,
        8,
        8,
        30,
        88,
        "8#|#@ #.2 #|#2 #3 #|#2 #3 #|# $ #$ #|# $4 #|4#2. #|3=5#",
    },

    {
        /*
        =======####|
        =======#  #|
        ====####  #|
        =####     #|
        =#    .##$#|
        =#  ##*## #|
        =## ##@## #|
        ==# ##$## ##|
        ### ## ##  #|
        #.         #|
        #   ########|
        #####
        Collection/Set: Atlas04
        Serial Number: 3
        Name: Atlas04 3
        Author: Eric F Tchong
        Width: 12
        Height: 12
        Nb Boxes: 3
        Pushes: 46
        Moves: 88

        */

        3,
        12,
        12,
        46,
        88,
        "7=4#|7=#2 #|4=4#2 #|=4#5 #|=#4 .2#$#|=#2 2#*2# #|=2# 2#@2# #|2=# 2#$2# 2#|3# 2# 2#2 #|#.9 "
        "#|#3 8#|5#",

    },

    {

        /*

"####=####|
"#  ###  #|
"#   . $@#|
"# $ .$$ #|
"### . ###|
"==# . #|
"==#####
Collection/Set: Li Jin You Collection
Serial Number: 181
Name: Li Jin You Collection 181
Author: Li Jin You
Width: 9
Height: 7
Nb Boxes: 4
Pushes: 24
Moves: 89

        */

        181,
        9,
        7,
        24,
        89,
        "4#=4#|#2 3#2 #|#3 . $@#|# $ .2$ #|3# . 3#|2=# . #|2=5#",

    },

    {

        /*
        "####|"
        "#  #|"
        "#  #####|"
        "#  $   #|"
        "##$* * #|"
        "#  .# ##|"
        "#.  @ #|"
        "#######"
        Collection/Set: Scoria 2
        Serial Number: 2
        Name: Scoria 2 2
        Author: Thomas Reinke
        Width: 8
        Height: 8
        Nb Boxes: 4
        Pushes: 35
        Moves: 152

        */
        2,
        8,
        8,
        35,
        152,
        "4#|#2 #|#2 5#|#2 $3 #|2#$* * #|#2 .# 2#|#.2 @ #|7#",
    },

    {

        /*

        "====########|"
        "#####      #|"
        "#    #  $  #|"
        "# $#$ ..#$##|"
        "#     ..   #|"
        "####  .. ###|"
        "===#   #$#|"
        "===###$@ #|"
        "=====#   #|"
        "=====#####"
        Collection/Set: Spiros 06
        Serial Number: 14
        Name: Spiros 06 14
        Author: Spiros Mantzoukis
        Width: 12
        Height: 10
        Nb Boxes: 6
        Pushes: 38
        Moves: 152

        */

        14,
        12,
        10,
        38,
        152,
        "4=8#|5#6 #|#4 #2 $2 #|# $#$ 2.#$2#|#5 2.3 #|4#2 2. 3#|3=#3 #$#|3=3#$@ #|5=#3 #|5=5#",

    },

    {
        /*

        Collection/Set: COSMONOTES
        Serial Number: 15
        Name: COSMONOTES #15
        Author: Aymeric du Peloux
        Width: 8
        Height: 7
        Nb Boxes: 4
        Pushes: 30
        Moves: 88

             #####
             #@. #
            ##$.$##
            #  *  ##
            #  .$  #
            ####   #
               #####
        */

        5001,
        8,
        7,
        30,
        88,
        "=5#|=#@. #|2#$.$2#|#2 *2 2#|#2 .$2 #|4#3 #|3=5#",

    },

    {

        /*
        #####|
        #   #|
        #   #|
        ##  ########|
        =#  ..##   #|
        ##  @.## # #|
        #        $ #|
        #  ### $####|
        #  #=#  #|
        ####=# $#|
        =====#  #|
        =====####
        Collection/Set: Marko Dzekic
        Serial Number: 24
        Name: Marko Dzekic 24
        Author: Marko Dzekic
        Width: 12
        Height: 12
        Nb Boxes: 3
        Pushes: 62
        Moves: 152

        */
        24,
        12,
        12,
        62,
        152,
        "5#|#3 #|#3 #|2#2 8#|=#2 2.2#3 #|2#2 @.2# # #|#8 $ #|#2 3# $4#|#2 #=#2 #|4#=# $#|5=#2 "
        "#|5=4#",
    },

    {

        /*
        ===#####|
        ===#   #|
        =### # ###|
        ## $. .  #|
        #  #.#.#$##|
        #  $.#. $@#|
        #  $* *$$ #|
        ##  . . $ #|
        =##########
        Collection/Set: Kevin 13
        Serial Number: 71
        Name: Kevin 13 71
        Author: Kevin B. Reilly
        Width: 11
        Height: 9
        Nb Boxes: 10
        Pushes: 78
        Moves: 322


        */

        71,
        11,
        9,
        78,
        322,
        "3=5#|3=#3 #|=3# # 3#|2# $. .2 #|#2 #.#.#$2#|#2 $.#. $@#|#2 $* *2$ #|2#2 . . $ #|=10#",

    },

    {

        /*

        ###################|
        #                 #|
        # .$* * * * * * * #|
        #  * * * * * * *  #|
        # * * * * * * * * #|
        #  * * * * * * *  #|
        # * * * * * * * * #|
        #  * * * *@* * *  #|
        # * * * * * * * * #|
        #  * * * * * * *  #|
        # * * * * * * * * #|
        #  * * * * * * *  #|
        # * * * * * * * * #|
        #  * * * * * * *  #|
        #                 #|
        ###################
        Collection/Set: Svens Collection
        Serial Number: 42
        Name: Svens Collection 42
        Author: Sven Egevad
        Width: 19
        Height: 16
        Nb Boxes: 90
        Pushes: 343
        Moves: 3894

        */

        42,
        19,
        16,
        343,
        3894,
        "19#|#17 #|# .$* * * * * * * #|#2 * * * * * * *2 #|# * * * * * * * * #|#2 * * * * * * *2 "
        "#|# * * * * * * * * #|#2 * * * *@* * *2 #|# * * * * * * * * #|#2 * * * * * * *2 #|# * * * "
        "* * * * * #|#2 * * * * * * *2 #|# * * * * * * * * #|#2 * * * * * * *2 #|#17 #|19#",

    },

    {
        //      ###
        // ######@##
        // #    .* #
        // #   #   #
        // #####$# #
        //     #   #
        //     #####

        -1,
        9,
        7,
        -1,
        -1,
        "5=3#|6#@2#|#4 .* #|#3 #3 #|5#$# #|4=#3 #|4=5#",
    },

    {
        // ######
        // #    #
        // # #@ #
        // # $* #
        // # .* #
        // #    #
        // ######

        -1,
        6,
        7,
        -1,
        -1,
        "6#|#4 #|# #@ #|# $* #|# .* #|#4 #|6#",

    },

    {
        //  ####
        // ##  ###########
        // #@$ .$  $  $  #
        // # $* .$.*.*.*.#
        // ## *$  $      #
        //  # . ##########
        //  # . #
        //  #####

        -1,
        15,
        8,
        -1,
        -1,
        "=4#|2#2 11#|#@$ .$2 $2 $2 #|# $* .$.*.*.*.#|2# *$2 $6 #|=# . 10#|=# . #|=5#",
    },

    {
        //   ########
        //  ##  . . #
        //  # *$# # #
        //  #.  #$# ##
        // ##* #  #  #
        // #   # *   #
        // # $#@ .#  #
        // #     $ ###
        // ##  #   #
        //  ########

        -1,
        11,
        10,
        -1,
        -1,
        "2=8#|=2#2 . . #|=# *$# # #|=#.2 #$# 2#|2#* #2 #2 #|#3 # *3 #|# $#@ .#2 #|#5 $ 3#|2#2 #3 "
        "#|=8#",

    },
#endif
};

struct stats roomStats[sizeof(room) / sizeof(room[0])];

static short firstX = 999;
static short firstY = 999;
static short lastX = 0;
static short lastY = 0;

short unpackLength;

void putObject(int *x, int y, unsigned char ch, int length) {

	if (!length)
		length = 1;

	unsigned char *board = ADDRESS_OF(y) + *x;
	for (int i = 0; i < length; i++) {
		*board++ = ch;

		if (ch == CH_PILL_1)
			pillCount++;
	}

	*x += length;
	unpackLength = 0;
}

int getRoomCount() { return sizeof(room) / sizeof(room[0]); }

int getRandomRoomNumber() { return rangeRandom(getRoomCount()); }

void setScroll() {

	int playerShoePixelX = manX * PIXELS_PER_CHAR + (PIXELS_PER_CHAR / 2) - 160 / 10;
	scrollX[DISPLAY_NORMAL] = playerShoePixelX << SHIFT_SCROLLX;
	clamp(&scrollX[DISPLAY_NORMAL], SCROLL_MAXIMUM_X_NORMAL);

	int playerShoePixelY = (manY + 1) * CHAR_HEIGHT / 3 - _ICC_SCANLINES / 2;
	scrollY[DISPLAY_NORMAL] = playerShoePixelY << SHIFT_SCROLLY;
	clamp(&scrollY[DISPLAY_NORMAL], SCROLL_MAXIMUM_Y_NORMAL);

	playerShoePixelX = manX * 3;
	scrollX[DISPLAY_HALF] = playerShoePixelX << SHIFT_SCROLLX;
	clamp(&scrollX[DISPLAY_HALF], SCROLL_MAXIMUM_X_HALF);

	playerShoePixelY =
	    (manY + 1) * CHAR_HEIGHT_HALF / 3 - (_ICC_SCANLINES - SCORE_SCANLINES / 3) / 2;
	scrollY[DISPLAY_HALF] = playerShoePixelY << SHIFT_SCROLLY;
	clamp(&scrollY[DISPLAY_HALF], SCROLL_MAXIMUM_Y_HALF);
}

void clearBoard(char ch) {

	unsigned char *board = ADDRESS_OF(0);
	for (int i = 0; i < __BOARD_SIZE; i++)
		board[i] = ch;

	//    zeroBuffer((int *)ADDRESS_OF(0), __BOARD_SIZE / 4); }
}

void initRooms() {
	for (int i = 0; i < sizeof(roomStats) / sizeof(roomStats[0]); i++)
		roomStats[i] = (struct stats){0, 0, 0};
}

void unpackRoom(int roomNumber) {

	pillCount = 0;

	int left = (__BOARD_WIDTH - room[roomNumber].width) >> 1;

	int x = left;
	int y = (__BOARD_DEPTH - room[roomNumber].height) >> 1;

	unpackLength = 0;

	clearBoard(CH_STEELWALL);

	const char *p = room[roomNumber].design;
	while (*p) {

		switch (*p) {
		case NEXTLINE:
			y += unpackLength ? unpackLength : 1;
			x = left;
			break;

		case STEEL:
			putObject(&x, y, CH_STEELWALL, unpackLength);
			break;

		case WALL:
			putObject(&x, y, CH_BRICKWALL, unpackLength);
			break;

		case PLAYERONNORMAL:
			manX = x;
			manY = y;

			putObject(&x, y, CH_BLANK, unpackLength);
			break;

		case BOXONTARGET:
			putObject(&x, y, CH_BOX_LOCKED, unpackLength);
			break;

		case PLAYERONGOAL:
			manX = x;
			manY = y;

			putObject(&x, y, CH_PILL_1, unpackLength);
			break;

		case TARGET:
			putObject(&x, y, CH_PILL_1, unpackLength);
			break;

		case GAP:
		case GAP2:
		case GAP3:
			putObject(&x, y, CH_BLANK, unpackLength);
			break;

		case BOX:
			putObject(&x, y, CH_BOX, unpackLength);
			break;

		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
			unpackLength = 10 * unpackLength + (*p - '0');
			break;

		default:
			break;
		}

		p++;
	}

	setScroll();
}

// EOF
